BlogCore/Areas/Admin/Controllers/ArticulosController.cs
using BlogCore.AccesoDatos.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArticulosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        public ArticulosController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo; 
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        #region llamada Api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Articulo.GetAll(includeProperties: "Categoria") });
        }

        #endregion
    }
}

BlogCore/Areas/Cliente/Controllers/HomeController.cs
using System.Diagnostics;
using BlogCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Cliente.Controllers
{
    [Area("Cliente")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogCore/Areas/Admin/Views/Articulos/Index.cshtml
@{
    ViewData["Title"] = "Lista de Articulos";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2 class="text-primary">
                Lista de Articulos
            </h2>
        </div>
        <div class="col-4 text-right">
            <a asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus">Crear nuevo Articulo</i>
            </a>
        </div>
    </div>
    <<br />
    <br />

    <table id="tblArticulos" class="table table-striped table-bordered" style="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Fecha Creacion</th>
                <th>Acciones</th>
            </tr>
        </thead>

    </table>
</div>

@section Scripts {
    <script src="~/js/Articulos.js"></script>
}

BlogCore/Areas/Admin/Views/Categorias/Create.cshtml
@model BlogCore.Modelos.Categoria; 

@{
    ViewData["Title"] = "Crear Categoria";
}

<br/>
</br>

<h3  class="text-center">Crear una categoria nueva </h3>
<form method="post" asp-action="Create">
    <div class="form-group row">
        <div class="col-4">
            <label asp-for="Nombre"></label>
        </div>
        <div class="col-8">
            <input asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre" />
        </div>
    </div>
    <br />
    <br />
    <div class="form-group row">
        <div class="col-4">
            <label asp-for="Orden"></label>
        </div>
        <div class="col-8">
            <input asp-for="Orden" class="form-control" placeholder="Ingresa el Orden" />
        </div>
    </div>

    <div class="form-group-row">
        <div class="col-8">
            <partial name="_VistaCrearVolver" />
        </div>
    </div>
</form>

BlogCore/Areas/Admin/Views/Categorias/Edit.cshtml
 @model BlogCore.Modelos.Categoria; 

@{
    ViewData["Title"] = "Editar Categoria";
}

<br/>
</br>

<h3  class="text-center">Editar  una categoria </h3>
<form method="post" asp-action="Create">
    <div class="form-group row">
        <div class="col-4">
            <label asp-for="Nombre"></label>
        </div>
        <div class="col-8">
            <input asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre" />
        </div>
    </div>
    <br />
    <br />
    <div class="form-group row">
        <div class="col-4">
            <label asp-for="Orden"></label>
        </div>
        <div class="col-8">
            <input asp-for="Orden" class="form-control" placeholder="Ingresa el Orden" />
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary form-control">Editar Categoria</button>
        </div>

        <div class="col">
            <a asp-action="Index" class="btn btn-success form-control">Volver Atras</a>
        </div>
    </div>
</form>

BlogCore/Areas/Admin/Views/Categorias/Index.cshtml
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2 class="text-primary">
                Lista de Categorias
            </h2>
        </div>
        <div class="col-4 text-right">
            <a asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus">Crear nueva Categoria</i>
            </a>
        </div>
    </div>
    <<br />
    <br />

    <table id="tblCategorias" class="table table-striped table-bordered" style="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Orden</th>
                <th>Acciones</th>
            </tr>
        </thead>

    </table>
</div>

@section Scripts  {
    <script src="~/js/Categoria.js"></script>
}

BlogCore/Areas/Cliente/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlogCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogCore</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
    @* <link rel="stylesheet" href="~/BlogCore.styles.css" asp-append-version="true" /> *@
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">
                            Inicio
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="admin" asp-controller="Categorias" asp-action="Index">Categoria</a>
                            <a class="dropdown-item" asp-area="admin" asp-controller="Articulos" asp-action="Index">Articulos</a>
                            <a class="dropdown-item" asp-area="admin" asp-controller="Sliders" asp-action="Index">Sliders</a>

                            <a class="dropdown-item" asp-area="admin" asp-controller="Usuarios" asp-action="Index">Usuarios </a>

                        </div>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
            <partial name="_LoginPartial" />
        </div>
    </nav>

    
    <header>
     

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" >
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">Inicio</a>

                                </div>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
          

        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - BlogCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.5/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogCore/Views/Shared/_VistaCrearVolver.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear</button>
    </div>

    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Volver atras</a>
    </div>
</div>